// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// PathRewriter adds an HTMX configRequest interceptor that rewrites bare page paths
// (e.g. "/crons/detail") to fully-qualified dashboard extension paths
// (e.g. "/dashboard/ext/dispatch/pages/crons/detail").
//
// It also rewrites API paths starting with "/v1/" by prepending the extension's
// API base path (e.g. "/v1/jobs/..." becomes "/dispatch/v1/jobs/...").
//
// This component should wrap the outermost page content once.
func PathRewriter(pagesBase string, apiBase string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div data-dispatch-pages-base=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(pagesBase)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard/components/path_rewriter.templ`, Line: 12, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-dispatch-api-base=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(apiBase)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard/components/path_rewriter.templ`, Line: 12, Col: 77}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><script>\n\t(function(){\n\t\tif (window.__dispatchPathRewriterAttached) return;\n\t\twindow.__dispatchPathRewriterAttached = true;\n\n\t\tdocument.addEventListener('htmx:configRequest', function(e) {\n\t\t\tvar el = e.detail.elt;\n\t\t\tvar wrapper = el.closest('[data-dispatch-pages-base]');\n\t\t\tif (!wrapper && document.querySelector('[data-dispatch-pages-base]')) {\n\t\t\t\twrapper = document.querySelector('[data-dispatch-pages-base]');\n\t\t\t}\n\t\t\tif (!wrapper) return;\n\n\t\t\tvar base = wrapper.getAttribute('data-dispatch-pages-base');\n\t\t\tvar apiBase = wrapper.getAttribute('data-dispatch-api-base');\n\t\t\tif (!base) return;\n\n\t\t\tvar dashBase = base.replace(/\\/ext\\/[^/]+\\/pages$/, '');\n\t\t\tvar path = e.detail.path;\n\t\t\tif (!path || !path.startsWith('/')) return;\n\n\t\t\t// Already fully qualified — dashboard path\n\t\t\tif (path.startsWith(base)) return;\n\n\t\t\t// Already fully qualified — API path with extension prefix\n\t\t\tif (apiBase && path.startsWith(apiBase + '/')) return;\n\n\t\t\t// API paths — prepend extension API base\n\t\t\tif (path.startsWith('/v1/') && apiBase) {\n\t\t\t\te.detail.path = apiBase + path;\n\t\t\t\treturn;\n\t\t\t}\n\n\t\t\t// Partial ext path (from htmx.ajax calls) — add dashboard prefix\n\t\t\tif (path.startsWith('/ext/')) {\n\t\t\t\te.detail.path = dashBase + path;\n\t\t\t\treturn;\n\t\t\t}\n\n\t\t\t// Bare page path — add full prefix\n\t\t\te.detail.path = base + path;\n\t\t});\n\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
